spring:
  application:
    name: springbootjdbc-htmx-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/products_db?currentSchema=products
    username: products_user
    password: password
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: products
    placeholders:
      schema_owner: products_user

  thymeleaf:
    cache: false

server:
  port: 8080

logging:
  level:
    com.example.demo: DEBUG

app:
  upload:
    dir: ${user.dir}/uploads
